//  for VACANCY_REDUCER
export const SET_VACANCY = "SET_VACANCY";
export const GET_VACANCY_BY_ID = "GET_VACANCY_BY_ID";
export const GET_ALL_VACANCY = "GET_ALL_VACANCY";

//  for MESSAGE_REDUCER
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//  for AUTH_REDUCER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const PIN_SUCCESS = "PIN_SUCCESS";
export const PIN_FAIL = "PIN_FAIL";

export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";

export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAIL = "FORGOT_PASS_FAIL";

export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAIL = "CHANGE_PASS_FAIL";


// for PROFILE_REDUCER
export const GET_ACADEMIC_DEGREE_SUCCESS = "GET_ACADEMIC_DEGREE_SUCCESS";
export const GET_ACADEMIC_TITLE_SUCCESS = "GET_ACADEMIC_TITLE_SUCCESS";
export const GET_ARTICLE_TYPE_SUCCESS = "GET_ARTICLE_TYPE_SUCCESS";
export const GET_DEVELOPMENT_TYPE_SUCCESS = "GET_DEVELOPMENT_TYPE_SUCCESS";
export const GET_PROJECT_TYPE_SUCCESS = "GET_PROJECT_TYPE_SUCCESS";
export const GET_REQUEST_BY_ID_SUCCESS = "GET_REQUEST_BY_ID_SUCCESS";

export const DOCUMENT_CREATE_SUCCESS = "DOCUMENT_CREATE_SUCCESS";
export const DOCUMENT_CREATE_FAIL = "DOCUMENT_CREATE_FAIL";

export const ARTICLE_CREATE_SUCCESS = "ARTICLE_CREATE_SUCCESS";
export const ARTICLE_CREATE_FAIL = "ARTICLE_CREATE_FAIL";

export const USER_PROFESSIONAL_INFO_CREATE_SUCCESS = "USER_PROFESSIONAL_INFO_CREATE_SUCCESS";
export const USER_PROFESSIONAL_INFO_CREATE_FAIL = "USER_PROFESSIONAL_INFO_CREATE_FAIL";

export const CERTIFICATE_CREATE_SUCCESS = "CERTIFICATE_CREATE_SUCCESS";
export const CERTIFICATE_CREATE_FAIL = "CERTIFICATE_CREATE_FAIL";

export const DEVELOPMENT_CREATE_SUCCESS = "DEVELOPMENT_CREATE_SUCCESS";
export const DEVELOPMENT_CREATE_FAIL = "DEVELOPMENT_CREATE_FAIL";

export const INTELLIGENCE_LEGAL_DOCUMENTS_CREATE_SUCCESS = "INTELLIGENCE_LEGAL_DOCUMENTS_CREATE_SUCCESS";
export const INTELLIGENCE_LEGAL_DOCUMENTS_CREATE_FAIL = "INTELLIGENCE_LEGAL_DOCUMENTS_CREATE_FAIL";

export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";

export const REQUEST_CREATE_SUCCESS = "REQUEST_CREATE_SUCCESS";
export const REQUEST_CREATE_FAIL = "REQUEST_CREATE_FAIL";









