//  for VACANCY_REDUCER
export const SET_VACANCY = "SET_VACANCY";

//  for SIGN_UP_REDUCER and SIGN_IN_REDUCER
export const UPDATE_FIRST_NAME = "UPDATE_FIRST_NAME";
export const UPDATE_LAST_NAME = "UPDATE_LAST_NAME";
export const UPDATE_PATRONYMIC = "UPDATE_PATRONYMIC";
// export const UPDATE_PHONE_NUMBER = "UPDATE_PHONE_NUMBER";
export const UPDATE_EMAIL_ADDRESS = "UPDATE_EMAIL_ADDRESS";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

//  for MESSAGE_REDUCER
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//  for AUTH_REDUCER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const PIN_SUCCESS = "PIN_SUCCESS";
export const PIN_FAIL = "PIN_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAIL = "FORGOT_PASS_FAIL";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAIL = "CHANGE_PASS_FAIL";

//  for VACANCY_REDUCER
export const GET_VACANCY_BY_ID = "GET_VACANCY_BY_ID";
export const GET_ALL_VACANCY = "GET_ALL_VACANCY";

